// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAohuXz1R8d1_YTqcPOVpql4nddVT9kk_A',
    appId: '1:179726593305:web:0b15e1d2f3d990861d6988',
    messagingSenderId: '179726593305',
    projectId: 'learning-16eca',
    authDomain: 'learning-16eca.firebaseapp.com',
    storageBucket: 'learning-16eca.appspot.com',
    measurementId: 'G-MFG838Z0LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-BOfnHUJ5Oi4X0Wy929dXgCSW0yt7mxY',
    appId: '1:179726593305:android:93f4b759175f9f761d6988',
    messagingSenderId: '179726593305',
    projectId: 'learning-16eca',
    storageBucket: 'learning-16eca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg4NLkWqJwJBlgqNjFmCY3kCQB0JSF4u4',
    appId: '1:179726593305:ios:a88867c785d4554a1d6988',
    messagingSenderId: '179726593305',
    projectId: 'learning-16eca',
    storageBucket: 'learning-16eca.appspot.com',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg4NLkWqJwJBlgqNjFmCY3kCQB0JSF4u4',
    appId: '1:179726593305:ios:35b829ed80a916b01d6988',
    messagingSenderId: '179726593305',
    projectId: 'learning-16eca',
    storageBucket: 'learning-16eca.appspot.com',
    iosBundleId: 'com.example.testing.RunnerTests',
  );
}
